---
# Title: Mailcow server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/mailcow.yml
#
# Description:
#   This taskfile contains the settings for installing a Mailcow mailserver.
#
# Source(s):
#   - https://github.com/mailcow/mailcow-ansiblerole/
#
- name: "Git clone mailcow https://github.com/mailcow/mailcow-dockerized"
  ansible.builtin.git:
    repo: 'https://github.com/mailcow/mailcow-dockerized'
    dest: /opt/mailcow-dockerized
    #version: 

- name: "Unattended"
  ansible.builtin.blockinfile:
    path: /var/www/html/index.html
    marker: "# <!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertafter: "#!/usr/bin/env bash"
    block: |
      MAILCOW_HOSTNAME=test-name.bitfinity.net
      MAILCOW_TZ=Europe/Amsterdam
      MAILCOW_BRANCH=1
      SKIP_CLAMD=n
      
#- name: "docker compose pull"

#- name: "docker compose up -d"
