---
# Title: Mailcow server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/mailcow.yml
#
# Description:
#   This taskfile contains the settings for installing a Mailcow mailserver.
#
- name: "Git clone mailcow https://github.com/mailcow/mailcow-dockerized"
  ansible.builtin.git:
    repo: 'https://github.com/mailcow/mailcow-dockerized'
    dest: /opt/mailcow-dockerized
    #version: 
