---
# Title: Mailcow server
#
# Author: Bitfinity / L. Rutten
# Owner: Bitfinity / L. Rutten
#
# File: tasks/mailcow.yml
#
# Description:
#   This taskfile contains the settings for installing a Mailcow mailserver.
#
# Source(s):
#   - https://github.com/mailcow/mailcow-ansiblerole/
#
- name: "Check that the /opt/mailcow-dockerized/mailcow.conf exists on '{{ ansible_hostname }}'"
  ansible.builtin.stat:
    path: /opt/mailcow-dockerized/mailcow.conf
  register: stat_result_mailcow_conf
  
- name: "Git clone mailcow https://github.com/mailcow/mailcow-dockerized"
  ansible.builtin.git:
    repo: 'https://github.com/mailcow/mailcow-dockerized'
    dest: /opt/mailcow-dockerized
  when: not stat_result_mailcow_conf.stat.exists

- name: "Unattended"
  ansible.builtin.blockinfile:
    path:  /opt/mailcow-dockerized/generate_config.sh
    marker: "# <!-- {mark} ANSIBLE MANAGED BLOCK -->"
    insertafter: "#!/usr/bin/env bash"
    block: |
      MAILCOW_HOSTNAME=test-name.bitfinity.net
      MAILCOW_TZ=Europe/Amsterdam
      MAILCOW_BRANCH=1
      SKIP_CLAMD=n
  when: not stat_result_mailcow_conf.stat.exists
    
#- name: "docker compose pull"

#- name: "docker compose up -d"
